apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakF6TURZdwpOalExTkROYUZ3MDBNakF6TURZd05qUTFORE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDY0hjV2pKbEJQbkUvZ2QvYm93ZFZZMG1IMi9BdXJRZFI2UzQ5SXNYL0RhS2twdHZsTApuNEFkUVBZaU9nem9RZHhycTRVUFZwOGFudUx3NzNNSHc1RXBTUFRnTXg3dVN3SGJyYkRqNnM3ZmEvSlRsZ3dDCjdyb2oxcUNjc0tjSHdEbTVyS1NGUHpNNnVnbkFSQnFYd0x2Sm5sSTdlMDI3bGJyaytma2puOWpzR1pUY0NXbCsKSXhtaEFCcThtVXBDZHVYQTMwOTl3WkdLQ1FGRDdEU3lVa2NESVBEZmsrZlM2MWppNUUzM0lDWTltb1AwcURqdAozSUl2cXdwa0tPYVJFa09ra1F0NjFKSUdwa2hocE5OR0w0SDMvcFgydXUwMlNsaVVhbUdqYkUwdGQyRXI2bDVJCkhXZ1RPZkRaM0g0UzlNbHdVNS9lb2VLUzBMdFIrekZteU9sUEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRVOVBjNnVtbGVZbGZXSHR6UAo2L2Z5dEFDUVZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFoSUttYm4xOTdnc3BSakVmWERodHQydURGamNwCndRZDQ2ME9aem4veVY5czlrUUZ6RWN0QldBQ3kvZnhlMXE3TUN0eHIzYUxnZTJBVlVlNVJHTktIcWRoUW94djcKS05pZlY4SUl0dVV4eXJlT2MvN1NRVmx4NlN6VHh4azQzYVVIenFDQU84aUliSk5XMitLdEhxME5uQzhzOU5rMQp2VnBOdWZsYTBLR3BlOWNLL3lBN1IvVURZaFU0MTJnektYeFdacnRlQm9idThiblM5T25JMXF6dzhRcmxGeCtQCmpSclJ0OW9OdTBId2o0dVBGUjhJblBtUGd3cnpITmRBalNHQy93S3JSWTZiclJQc2ZOZ3J6YkR1WjR6RS9aa3oKd0dCejlFUk1WUVR2dkhsWGJTaXpYazRzdmlaRGlseDRjM1dtcGtudG9SODlwOEc0NEk2WGFxWXdzdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://92cf93bb-6260-44ef-ad5d-62fc6b3a12df.k8s.ondigitalocean.com
  name: do-blr1-k8s-pipeline
contexts:
- context:
    cluster: do-blr1-k8s-pipeline
    user: do-blr1-k8s-pipeline-admin
  name: do-blr1-k8s-pipeline
current-context: do-blr1-k8s-pipeline
kind: Config
preferences: {}
users:
- name: do-blr1-k8s-pipeline-admin
  user:
    token: 1179193f1cabdb9d18358cf1f0044033940a309cd278d4ba8b3e6811d7185f7a
