 
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: NodePort
  selector:
    app: django-k8s-web-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldb-configmap
data:
  MYSQL_HOST: django-mysql-service


---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: django1
  name: django-pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/docker/myFirstProject
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: djk8s-claim
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: djk8s-claim
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: django-pv1 # mount to this persistent volume
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s
        image: registry.digitalocean.com/django-k8s/djk8s_pipeline:v1.tagversion
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: dj-k8s-dev-sec
        env:
          - name: PORT
            value: "8000"
          - name: SQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysqldb-configmap
                key: MYSQL_HOST
        resources:
          limits:
            memory: "500Mi"
            cpu: "600m"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: django-persistent-storage
          mountPath: /djk8s
      imagePullSecrets:
        - name: django-k8s
      
      volumes:
      - name: django-persistent-storage
        persistentVolumeClaim:
          claimName: djk8s-claim
